
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_USER: db
      MARIADB_PASSWORD: db
      MARIADB_ROOT_PASSWORD: dbpw
      MARIADB_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - ../working-mariadb:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dbpw
      MONGO_INITDB_DATABASE: db
    ports:
      - "27017:27017"
    volumes:
      - ../working-mongodb:/data/db