  management:
    endpoints:
      web:
        exposure:
          include: health, beans
    endpoint:
      health:
        enabled: false
  spring:
    datasource:
      url: jdbc:mariadb://localhost:3306/flights
      username: root
      password: dbpw
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate
      open-in-view: false
    servlet:
      multipart:
        max-file-size: 5MB

  application:
    store:
      base-path: /home/matias/Escritorio/SpringTokio/flight-app-working-files

      # Logging para obtener mas detalles de las sentencias realizadas por Hibernate
  logging:
    level:
      org.hibernate.sql: trace
      org.hibernate.orm.jdbc.bind: trace