spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/airport_batch
    username: root
    password: dbpw
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

application:
  batch:
    base-path: /home/matias/Escritorio/SpringTokio/flight-app-batch-working-files